[build-system]
requires = [
    "setuptools", 
    "setuptools_scm[toml]",
    "setuptools_scm_git_archive",
    "wheel",
]

[tool.setuptools_scm]
write_to = "src/qualitor/version.py"
git_describe_command = "git describe --dirty --tags --long --match v* --first-parent"

